name: TPCore
version: '${version}'
main: com.lunatech.tpcore.TPCore
api-version: '1.20'
author: lunarenzo
description: High-performance, modular teleportation plugin for PaperMC and Folia.
folia-supported: true
